### ISSUE TITLE
Out of sample estimation

### ISSUE THREAD

**Issue by alfsn** [alfsn/regime-switching-hmm#23]
Para cada modelo necesito:
forecastear dia t
Restar real-forecast: eso es residuo t
Guardar la secuencia de residuos.
Hacer tests sobre las secuencias de residuos.

Para el out of sample:
1) **El fit() del modelo esta dentro del loop.** Es recursivo segun se vio la ultima observacion.
2) Mi window sea rolling (no recursive) porque es menos computacionalmente intensivo. 2 años de ventana esta ok, son 504 obs.

**Comment by alfredo-sampron** [comment]
Cierro igual que #27, closed by #36 and #43
