### ISSUE TITLE
HMM: crear una función que genere predicciones

### ISSUE THREAD

**Issue by alfsn** [alfsn/regime-switching-hmm#28]
Vamos a usar la función sample y decode en 
https://hmmlearn.readthedocs.io/en/latest/auto_examples/plot_hmm_sampling_and_decoding.html
https://hmmlearn.readthedocs.io/en/latest/api.html

**Comment by alfredo-sampron** [comment]
Closed by #29

**Comment by alfredo-sampron** [comment]
Closed by https://github.com/alfsn/regime-switching-hmm/pull/29
