### ISSUE TITLE
En el HMM tengo que reestimar en la rolling window

### ISSUE THREAD

**Issue by alfredo-sampron** [alfsn/regime-switching-hmm#41]

**Comment by alfredo-sampron** [comment]
Para generar forecasts:
> (fittear hasta t-j con 252d)
> Darle un año de datos hasta t-j para que me prediga la secuencia (probabilidad) de estados.
> Le pido que me prediga las probabilidades de cada estado durante el periodo t-j, t-j-252: esto me da una matriz de (252 x n estados)
> Tomo la ultima fila de la matriz 
> Multiplico esa por el vector de medias estimadas: este punto es mi forecast.

Pronostico alternativo:
Obtener vector de probabilidades de estado (1 prob por c/u de los n estados)
Obtener vector de medias de estado
Producto cartesiano de los dos vectores me da la estimación puntual
Es mucho más rico en información porque lo que estoy haciendo ahora me da lo mismo si el estado de max likelihood tiene p(x)=0.5 que si tiene 0.99.
Aca incorporo esa info.

**Comment by alfsn** [comment]
Implementado en #43

**Comment by alfsn** [comment]
Implementado en https://github.com/alfsn/regime-switching-hmm/pull/43
