### ISSUE TITLE
Comparación de modelos: test de Diebold y Mariano y test de Giacomini-White

### ISSUE THREAD

**Issue by alfsn** [alfsn/regime-switching-hmm#7]
Comparacion de pronostico puntual.
Diebold-Mariano: permite comparar dos modelos. H0 MSE_1=MSE_2

Comparaciòn de la cobertura del test:
Compara intervalos de confianza.
Giacomini-White

**Comment by alfredo-sampron** [comment]
Los tests deberán ser a una cola: 
Vamos a usar la función [plot_multivariate_DM_test](https://epftoolbox.readthedocs.io/en/latest/modules/statest/dm.html) porque nos ahorra de hacer uno por uno los tests y ya nos lo muestra bonito: 
![image](https://github.com/alfsn/regime-switching-hmm/assets/107074411/e41b95dd-a5b1-477c-a936-f61d999192b8)

Cuando el casillero es verde, los del eje x le ganan al eje y

**Comment by alfredo-sampron** [comment]
Implemented in #61

**Comment by alfredo-sampron** [comment]
Implemented in https://github.com/alfsn/regime-switching-hmm/pull/61
